---
  name: Tests and checks
  
  on:
    push:
      branches:
        - '*'
        - '*/*'
        - '**'
        - '!main'
  
  jobs:
    pr:
      uses: obervinov/_templates/.github/workflows/pr.yaml@v2.1.1

    pyproject:
      uses: obervinov/_templates/.github/workflows/pyproject.yaml@v2.1.1
